### ISSUE TITLE
精度不够是否是因为epoch太少

### ISSUE THREAD

**Issue by Mr-Z-NewStar** [yjh0410/PyTorch_YOLOF#3]

**Comment by yjh0410** [comment]
@Mr-Z-NewStar 训练epoch太少肯定是一个主要因素。不过，官方YOLOF就是训练12epoch，也就是coco上的标准1x训练策略~我实现的YOLOF收敛速度要比官方慢，具体原因还没有查出来，另外，可能后处理也有哪里实现得不太对劲~现在手头没有足够的资源来调试这个项目了，只能暂时搁置了~

**Comment by Mr-Z-NewStar** [comment]
你好，最近我十分需要复现YOLOF以其为基线来实现我的一个新想法，所以会尝试对代码进行修改完善并训练，能否加一下微信方便和您交流。
本人微信：2214366987

**Comment by Mr-Z-NewStar** [comment]
很喜欢您的代码结构，很清爽
